### ISSUE TITLE
[rfc] S3 backend for .gem files

### ISSUE THREAD

**Issue by indirect** [rubygems/gemstash#107]
I'm interested in extending Gemstash to use S3 to store private .gem files, instead of the filesystem. (Gems cached from RubyGems.org can continue to live on the local filesystem, since they can easily be regenerated on a new machine.)

This would theoretically make it easy and straightforward to blow away and spin up new web app server(s) as long as the Gemstash database is also stored externally in e.g. Postgres.

Mostly I'm opening this issue to request feedback. Does this seem like a good idea? Does this seem very hard? Does this seem like a clearly useful option? What about this am I not thinking of?

Thanks, everyone!

**Comment by smellsblue** [comment]
@indirect I think it's a great idea personally, and I think Gemstash is built in a way to support it... essentially the storage engine that uses the filesystem could be swapped out with one that uses S3 instead.

Would you prefer it be built in to Gemstash, or are you open to it being an extension?

**Comment by indirect** [comment]
I'm open to it being an extension... do we have a way to do that? I also feel like it's maybe reasonable as the one alternative to filesystems that we could put into core... offering one local and one distributed option in core seems defensible to me, with additional options being external gems? Or we could eventuall break out all the options into gems, gemstash-postgresql etc ¯\_(ツ)_/¯

**Comment by chriseckhardt** [comment]
👍  to this feature, this is a feature I've been meaning to hack on (just haven't made the time). Judging from https://github.com/bundler/gemstash/issues/85 it seems like a feature desired by others as well.

**Comment by indirect** [comment]
Oh man, how did I miss that. 😅  thanks for pointing it out, @chriseckhardt! I'd be happy to work together with you on it, starting sometime in the next 2-10 days.

**Comment by smellsblue** [comment]
@indirect there's no extension mechanism yet, though I've played with it in a branch. I think it's fine to be built into the core as well (I like the 1 local 1 remote argument).

If you and/or @chriseckhardt do work on it, let me know if you have any questions, or would like any additional help!

**Comment by indirect** [comment]
@smellsblue we would of course be ecstatic to have your help if you're available! otherwise I'll keep you posted. :)

**Comment by chriseckhardt** [comment]
Yeah that window lines up well with my schedule, actually. I'm pingable on Slack.

**Comment by pcarranza** [comment]
I've been quite out myself lately.

I like the idea, I think it will be ok to support S3 (or any other compatible storage system) in the core of the app. We just fallback to use filesystem by default.

Storage as a concepts is quite isolated from the rest of the application, shouldn't be too hard (famous last words)

**Comment by smellsblue** [comment]
I'll watch here and Slack as best I can :-)

A few questions from going over #85: is S3 going to be storage for both private and cached gems or just private? What about in case of S3 downtime? Will stuff be stored locally as well, or purely S3?

**Comment by indirect** [comment]
I was imagining that S3 would be the source of truth storage for private gems, just like it is for public gems today. Then gemstash can do the same pass through type caching that it does for those gems if the private gems aren’t present locally. S3 downtime seems far far less likely than gemstash downtime, and since it is where public gems come from as well, I think it’s panty for cache updates to not be possible during S3 downtime. 👍

**Comment by pcarranza** [comment]
I think that it's cheap to store the public gems locally (we can get them anytime anyway) but it gets tricky when we want to have more than 1 gemstash server to store private gems, this is when storing on S3 actually makes sense to me.

**Comment by CpuID** [comment]
+1 this would be nice, mostly for the private gem storage. The cache part can be localised to a single instance, and repopulated on demand.

**Comment by yanowitz** [comment]
+1 for S3 storage (my use case: I want to store copies of all (public and private) gems so I can have reproducible deploys regardless of what happens in the outside world, and I'm looking to deploy using immutable containers). Is this actively being worked on?

**Comment by bronzdoc** [comment]
close via https://github.com/rubygems/gemstash/pull/270
