### ISSUE TITLE
Enable puma.sock config

### ISSUE THREAD

**Issue by akitaonrails** [rubygems/gemstash#114]
I don't know if it's an issue today or not, but I thought it would be interesting if we could enable the `puma.sock` through the `config.yml`

That way we would have it start up on the default 9292 port and also install an NGINX to open the same unix socket to enable other features such as SSL or event other forms of authentication.

Seems something simple to enable through `puma.rb` but I wanted to hear if there's a reason for it not being there already that I am not aware of.

**Comment by smellsblue** [comment]
@akitaonrails I think you can already do what you are describing, unless I am misunderstanding. We have a [`:bind` config variable](https://github.com/bundler/gemstash/blob/master/docs/gemstash-configuration.5.md#bind-address) you can set in your `config.yml` which specifies [how Gemstash should be binding](https://github.com/bundler/gemstash/blob/master/lib/gemstash/puma.rb#L4) with Puma. Thus, if you had your config pointing `:bind` to something like `unix:///var/run/puma.sock`, then it might do what you are describing.

Please let me know if this helps, or if you meant something different :-)

**Comment by bronzdoc** [comment]
@akitaonrails does @smellsblue answer solves your problem?

**Comment by bronzdoc** [comment]
Closing due to lack of response
