### ISSUE TITLE
Update RubyGems guide to hosting gems

### ISSUE THREAD

**Issue by indirect** [rubygems/gemstash#126]
At some point, we should update [the RubyGems guide to hosting your own gems](http://guides.rubygems.org/run-your-own-gem-server/) to remove the other options and tell people to use Gemstash. :)

**Comment by randycoulman** [comment]
I think this is a great idea, and should be done.  However, I'm wondering if there are few issues that should be addressed before this happens.  I'm most familiar with geminabox, and both of the following have affected my ability to migrate to gemstash:

* #129 
* #76

There's also #72, but I don't know enough to say if that should be considered a blocker or not.

**Comment by duckinator** [comment]
As a note, issue #129 has been resolved.

Perhaps it would be worth updating the guide to replace the discussion of `gem server` with `gemstash`, then remove the others once #76 (+ possibly #203) are resolved?

**Comment by duckinator** [comment]
DONE.

- Merged https://github.com/rubygems/guides/pull/266
- Opened https://github.com/rubygems/guides/pull/269
