### ISSUE TITLE
Errors on sources that don't implement /api/v1/dependencies

### ISSUE THREAD

**Issue by mcasper** [rubygems/gemstash#163]
We have a gem source that doesn't implement the `/api/v1/dependencies` API, which results in a 404 error when `gemstash` requests `<source>/api/v1/dependencies`. 

From running `bundler` with verbose output, it looks like `bundler` swallows that 404 and keeps going, eventually loading the source index and successfully getting the gem. `gemstash` raises an error when it gets the 404, causing the installation to fail. If I comment out the actual raising of the error in `gemstash`, it continues on like bundler and successfully downloads and caches the gem.

Is the 404 a legitimate thing that needs to be implemented by the source, or should `gemstash` be swallowing the error as `bundler` does?

**Comment by indirect** [comment]
Gemstash is designed to act as a mirror/cache for RubyGems.org, and so it was not designed to support sources that do not provide the dependencies API. If you're interested in adding support for sources without dependency APIs to Gemstash, you're welcome to start a discussion about it in this issue or a PR. 👍

**Comment by mcasper** [comment]
Sounds good! We've opened #164 to start the discussion
