### ISSUE TITLE
release jruby gem

### ISSUE THREAD

**Issue by andreaseger** [rubygems/gemstash#182]
Although it seems you're supporting jruby by e.g. testing against it on travis and adding special handling to some bits of the code for it you have not released a java gem for gemstash. https://rubygems.org/gems/gemstash

This will cause bundler to try installing `sqlite3` which won't work on jruby as it has native extensions.

This line won't be evaluated on gem usage but when the gem is build
https://github.com/bundler/gemstash/blob/master/gemstash.gemspec#L48

**Comment by olleolleolle** [comment]
@andreaseger Now here is a release I just did - see if that works well for you https://rubygems.org/gems/gemstash/versions/2.5.0-java

**Comment by andreaseger** [comment]
oh wow, totally forgot about having raised this issue (we switched to just run it on MRI).
Thanks for fixing this.

**Comment by olleolleolle** [comment]
@andreaseger Do you run it using a Docker container, or somehow else?

**Comment by andreaseger** [comment]
yes we run it on k8s with a very minimal dockerfile (ruby base image and just install gemstash). Runs as a statefulset and also has a memcached server.  Acting as in-cluster gem cache for CI and is also used by some devs.
Runs so stable that we almost never have to touch it.
