### ISSUE TITLE
gemstash status returns nothing

### ISSUE THREAD

**Issue by ericzpd** [rubygems/gemstash#251]
Running `gemstash status` command returns nothing on my machine. Is it expected?

- Ruby 2.5.7
- Gemstash 2.0.0

**Comment by bronzdoc** [comment]
No, that is not expected. Thanks for the report @ericzpd!

**Comment by ericzpd** [comment]
@bronzdoc The `pumactl status` for pidfile is added a few months ago and is available after Puma 4.0. Gemstash is using `puma ~> 3.10` now. Maybe it should be upgraded to Puma 4.

Ref https://github.com/puma/puma/commit/5a2291ef1bc339138eecf6f736fb769c8c6891ac

**Comment by bronzdoc** [comment]
I was just looking at this issue, Thanks @ericzpd!
