### ISSUE TITLE
force option to fetch from rubygems_url instead of Gemfile source

### ISSUE THREAD

**Issue by zpdcodes** [rubygems/gemstash#252]
I want to use `https://gems.ruby-china.com` for mirroring `https://rubygems.org` in all Gemfiles, while keeping gemstash caching. 

- Bundler mirror config: `bundle config mirror.https://rubygems.org http://localhost:9292`.
- Gemstash config: `:rubygems_url: https://gems.ruby-china.com`.

However, gemstash will use source url from Gemfile, if it exists, to fetch original gems, ignoring `rubygems_url` config. 

Is it any way to force gemstash to fetch from `rubygems_url`?

**Comment by bronzdoc** [comment]
Closed by https://github.com/rubygems/gemstash/pull/253
