### ISSUE TITLE
Release new version of gem

### ISSUE THREAD

**Issue by aleksey-hariton** [rubygems/gemstash#254]
Hey people,

could someone please release new gem version from current `master`?

Actually in current released version usage of any other database connection except `sqlite3` doesn't work for private gems, one can push gem and install it if there is no dependencies specified, if gem have any deps gemstash returning 500, same as in #189 

Tested current master with Postgres, it works pretty well.

**Comment by aleksey-hariton** [comment]
@bronzdoc any news?

**Comment by bronzdoc** [comment]
https://github.com/rubygems/gemstash/blob/master/CHANGELOG.md
