### ISSUE TITLE
[Feature Request] More detailed gemstash status command

### ISSUE THREAD

**Issue by duyquangnguyenhac** [rubygems/gemstash#273]
Currently, the gemstash status command only reports on whether or not the Puma server has been started. I figure it would be more intuitive to have the command report on current configurations settings. For example if the sqlite3 cache backend was selected, the user can easily find out what choice was made during the setup process and what is currently running.

Even more so, it could also report on what gems are currently loaded on the server right now. So basically stating the names of the gems that currently on the server's storage. I think right now the gems could only be checked if it's on the server and not yanked already is through it's 'indexed' status which can't be easily accessed.

**Comment by bronzdoc** [comment]
Closed via https://github.com/rubygems/gemstash/issues/273
