### ISSUE TITLE
Serve all gems from /private?

### ISSUE THREAD

**Issue by nearapogee** [rubygems/gemstash#286]
With `bundler` 2.2.9 this worked:

```
source "https://rubygems.org"

gem 'rails'

source "https://some.server.com/private" do
  gem 'my-private-gem'
end
```

After `bundler` 2.2.10, you have to specify a source for all gems, if you use source for one, in block or on an individual gem. So if you try the above you will get:

```
Fetching gem metadata from https://some.server.com/private/...
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://some.server.com/private/..
Resolving dependencies...
The gem 'bundler' was found in multiple relevant sources.
  * rubygems repository https://some.server.com/private/ or installed locally
  * rubygems repository https://rubygems.org/ or installed locally
You must add this gem to the source block for the source you wish it to be installed from.
```

It seems they want you to do this:
```
source "https://some.server.com/private"

gem 'rails'
gem 'my-private-gem'
```

Because even if you wrap the other dependencies (rails in this case) in a source block you will get the same error.... because the source for `bundler` wasn't explicitly stated.

Would it be possible to add an option to allow `/private` to serve all cached gems? If I am understanding the logs and the source correctly it is rewritting them out of the `/private` location.

The alternative seems that the security enhancement of `bundler` v2.2.10 is too tight. But I would rather just specify one source and be done with it.

Right now the only solution I can figure out is to lock `bundler` at 2.2.9

**Comment by olleolleolle** [comment]
Assessment: The fix is coming to Bundler, this is not a workaround Gemstash should build.

https://github.com/rubygems/rubygems/pull/4381

**Comment by nearapogee** [comment]
@olleolleolle Awesome - Thanks for finding/pointing that out!
