### ISSUE TITLE
Change build badge for the GH actions one

### ISSUE THREAD

**Issue by bronzdoc** [rubygems/gemstash#294]
We migrated to Github Actions but we are still showing the old travis build badge. We need to replace it for the GH one
![Screen Shot 2021-04-04 at 11 26 39 PM](https://user-images.githubusercontent.com/4595174/113540439-657c9680-959d-11eb-983f-211bb51e0198.png)

**Comment by mushahidq** [comment]
I've created a pull request for this. #295

**Comment by bronzdoc** [comment]
@Thanks @mushahidq! 

Closed by https://github.com/rubygems/gemstash/pull/295#issuecomment-813308835
