### ISSUE TITLE
Fix JRuby 9.4 install failure re Bigdecimal 3.1.4

### ISSUE THREAD

**Issue by olleolleolle** [rubygems/gemstash#358]
In #355, a non-related JRuby install failure showed up. 

EDIT: Sequel gem depends on bigdecimal, now. And there is no -java gem release for bigdecimal, yet.

```
In Gemfile:
  gemstash was resolved to 2.3.0, which depends on
    sequel was resolved to 5.72.0, which depends on
      bigdecimal
```

**Comment by olleolleolle** [comment]
Locally, I was unable to install gemstash with JRuby 9.4

I got this sort of error:

```
$ rvm use jruby-9.4
Using /Users/olle/.rvm/gems/jruby-9.4
$ bundle
Could not find gem 'gemstash x86_64-darwin-19' in source at `.`.

The source contains the following gems matching 'gemstash':
  * gemstash-2.3.0-java
```

**Comment by headius** [comment]
So it seems that sequel now depends on the bigdecimal gem, which has no JRuby version. Our best option going forward would be to help the bigdecimal maintained create a stub -java version of the gem, which must be released with every bigdecimal version.
