### ISSUE TITLE
Authorization tokens are easy to lose track of

### ISSUE THREAD

**Issue by kyrofa** [rubygems/gemstash#364]
We've been using the private gem functionality of gemstash for a number of years now, with great success. However, as both our team and our CI systems have changed a little over time, we're hitting a pain point: we need to keep careful notes of which token belongs to each developer or system, so we can revoke tokens when they're no longer used. This feels like a feature that could be easily added to gemstash, and if we agree on a design I'd be happy to add it. I'm thinking something really simple:

- The ability to name or label a given authorization.
- The ability to list authorizations, with their names and capabilities

Thoughts?

**Comment by kyrofa** [comment]
I see #165, for example, but it didn't appear to ever get any traction and appears dead at this point.

**Comment by indirect** [comment]
Yeah, some sort of name or label sounds great! Thanks for offering.

**Comment by kyrofa** [comment]
Thanks for the feedback, @indirect! I realize I missed something above: a way to list the current authorizations, with their names and capabilities, to make sure you're revoking the right thing. Is that also something you'd support?

**Comment by indirect** [comment]
Yeah, absolutely.

**Comment by kyrofa** [comment]
Alright, keep an eye out for a PR then. Thanks for the quick responses!
