### ISSUE TITLE
Release a 2.7.1 supporting a --no-daemonize option that only outputs a warning

### ISSUE THREAD

**Issue by olleolleolle** [rubygems/gemstash#380]
>> Ah, then I am mistaken indeed, and I understand where you're coming from now. Thank you for your patience!
>
> Thanks for you patience as well, let's release the `2.7.1` soon adding back no-op `--no-daemonize` with warning.

_Originally posted by @simi in https://github.com/rubygems/gemstash/issues/378#issuecomment-1755974160_

**Comment by simi** [comment]
fixed by #381
